In [24]:
import pickle
vec = open("Tfidf_LogR_3.pickle", 'rb') # rb= read in bytes
grid3 = pickle.load(vec)
vec.close()

In [25]:
sample_text = "i hate you"

In [26]:
print(grid3.best_estimator_.named_steps['onevsrestclassifier'])
print(grid3.best_estimator_.named_steps['tfidfvectorizer'])

OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='sag',
          tol=0.0001, verbose=0, warm_start=False),
          n_jobs=None)
TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=30000, min_df=5,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents='unicode', sublinear_tf=False,
        token_pattern='\\w{1,}', tokenizer=None, use_idf=True,
        vocabulary=None)


In [27]:
predicted_sample_bad = grid3.predict([sample_text])

In [28]:
predicted_sample_bad

array([[1, 0, 0, 0, 0, 0]])

In [12]:
sample_text2 = "i love you"

In [13]:
predicted_sample_good = grid3.predict([sample_text2])

In [14]:
predicted_sample_good

array([[0, 0, 0, 0, 0, 0]])

In [15]:
# load in pickled models
from sklearn.externals import joblib

compressed = joblib.load('compressed_model.pkl')

In [16]:
predicted_sample_good = compressed.predict([sample_text2])

In [17]:
predicted_sample_good

array([[0, 0, 0, 0, 0, 0]])

In [18]:
recent = joblib.load('compressed_pipeline.pkl')

In [22]:
predicted_sample_good = recent.predict([sample_text2])

In [23]:
predicted_sample_good

array([[0, 0, 0, 0, 0, 0]])

In [29]:
labels = ['toxic', 'severe toxic', 'obscene', 'threat', 'insult', 'identity_hate']